// Generated by style-guide-creator. Tailwind CSS v3 preset: presets: [require('./tailwind.preset.js')]
// Semantic colours read CSS variables, so also include tokens.css.
module.exports = {
  "theme": {
    "extend": {
      "colors": {
        "primary": {
          "DEFAULT": "#5a3a29",
          "50": "#fcf5f2",
          "100": "#f8eae2",
          "200": "#eed5c8",
          "300": "#deb8a4",
          "400": "#c5967d",
          "500": "#ab795e",
          "600": "#8d5f47",
          "700": "#724a36",
          "800": "#5a3a29",
          "900": "#3d2518",
          "950": "#25130a"
        },
        "secondary": {
          "DEFAULT": "#2f5a45",
          "50": "#f2f9f5",
          "100": "#e3f1e9",
          "200": "#c9e2d4",
          "300": "#a6cbb7",
          "400": "#7eae95",
          "500": "#5e9478",
          "600": "#46785f",
          "700": "#2f5a45",
          "800": "#254837",
          "900": "#173225",
          "950": "#091d14"
        },
        "accent": {
          "DEFAULT": "#d9a441",
          "50": "#fdf6ea",
          "100": "#faebd2",
          "200": "#f2d7ab",
          "300": "#e3ba73",
          "400": "#d9a441",
          "500": "#ae7c00",
          "600": "#8d6300",
          "700": "#704e00",
          "800": "#553a00",
          "900": "#3b2700",
          "950": "#231500"
        },
        "neutral": {
          "50": "#f8f6f6",
          "100": "#eeeceb",
          "200": "#dedad8",
          "300": "#c6bfbc",
          "400": "#a7a09c",
          "500": "#8d8480",
          "600": "#726a66",
          "700": "#5a5450",
          "800": "#443e3c",
          "900": "#2e2a28",
          "950": "#140e0b"
        },
        "success": {
          "50": "#eefbf0",
          "100": "#dbf5df",
          "200": "#bae9c2",
          "300": "#8bd69a",
          "400": "#55ba70",
          "500": "#20a04e",
          "600": "#00823a",
          "700": "#00672c",
          "800": "#004e20",
          "900": "#003614",
          "950": "#001f08"
        },
        "warning": {
          "50": "#fff5e9",
          "100": "#fdead0",
          "200": "#f7d5a6",
          "300": "#ebb66a",
          "400": "#d59219",
          "500": "#b37900",
          "600": "#916100",
          "700": "#744c00",
          "800": "#573900",
          "900": "#3d2600",
          "950": "#241500"
        },
        "error": {
          "50": "#fff4f2",
          "100": "#ffe6e3",
          "200": "#ffcdc6",
          "300": "#ffa69b",
          "400": "#ee7b6f",
          "500": "#d5584f",
          "600": "#b33f38",
          "700": "#922e28",
          "800": "#701f1b",
          "900": "#50120f",
          "950": "#320605"
        },
        "info": {
          "50": "#f1f8ff",
          "100": "#e0efff",
          "200": "#c0deff",
          "300": "#8fc6ff",
          "400": "#53a6f7",
          "500": "#2389e2",
          "600": "#006ebe",
          "700": "#005798",
          "800": "#004174",
          "900": "#002c52",
          "950": "#001932"
        },
        "text-default": "var(--text-default)",
        "text-muted": "var(--text-muted)",
        "text-inverse": "var(--text-inverse)",
        "text-link": "var(--text-link)",
        "text-on-brand": "var(--text-on-brand)",
        "surface-default": "var(--surface-default)",
        "surface-subtle": "var(--surface-subtle)",
        "surface-inverse": "var(--surface-inverse)",
        "surface-brand": "var(--surface-brand)",
        "border-subtle": "var(--border-subtle)",
        "border-strong": "var(--border-strong)",
        "focus": "var(--focus)",
        "focus-on-brand": "var(--focus-on-brand)",
        "focus-on-primary": "var(--focus-on-primary)",
        "focus-on-secondary": "var(--focus-on-secondary)",
        "focus-on-accent": "var(--focus-on-accent)",
        "success-fg": "var(--success-fg)",
        "success-bg": "var(--success-bg)",
        "success-border": "var(--success-border)",
        "warning-fg": "var(--warning-fg)",
        "warning-bg": "var(--warning-bg)",
        "warning-border": "var(--warning-border)",
        "error-fg": "var(--error-fg)",
        "error-bg": "var(--error-bg)",
        "error-border": "var(--error-border)",
        "info-fg": "var(--info-fg)",
        "info-bg": "var(--info-bg)",
        "info-border": "var(--info-border)"
      },
      "fontFamily": {
        "display": [
          "'Fraunces', 'Iowan Old Style', 'Palatino Linotype', Palatino, Georgia, 'Times New Roman', serif"
        ],
        "body": [
          "'Source Sans 3', system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif"
        ],
        "mono": [
          "'JetBrains Mono', ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"
        ]
      },
      "fontSize": {
        "display": [
          "3.75rem",
          {
            "lineHeight": "1.1",
            "letterSpacing": "-0.02em",
            "fontWeight": "700"
          }
        ],
        "h1": [
          "3rem",
          {
            "lineHeight": "1.15",
            "letterSpacing": "-0.015em",
            "fontWeight": "700"
          }
        ],
        "h2": [
          "2.25rem",
          {
            "lineHeight": "1.2",
            "letterSpacing": "-0.01em",
            "fontWeight": "700"
          }
        ],
        "h3": [
          "1.75rem",
          {
            "lineHeight": "1.25",
            "letterSpacing": "0",
            "fontWeight": "600"
          }
        ],
        "h4": [
          "1.375rem",
          {
            "lineHeight": "1.3",
            "letterSpacing": "0",
            "fontWeight": "600"
          }
        ],
        "body-lg": [
          "1.25rem",
          {
            "lineHeight": "1.5",
            "letterSpacing": "0",
            "fontWeight": "400"
          }
        ],
        "body": [
          "1rem",
          {
            "lineHeight": "1.5",
            "letterSpacing": "0",
            "fontWeight": "400"
          }
        ],
        "small": [
          "0.875rem",
          {
            "lineHeight": "1.5",
            "letterSpacing": "0.01em",
            "fontWeight": "400"
          }
        ],
        "label": [
          "0.875rem",
          {
            "lineHeight": "1.4",
            "letterSpacing": "0.02em",
            "fontWeight": "600"
          }
        ],
        "code": [
          "0.9375rem",
          {
            "lineHeight": "1.5",
            "letterSpacing": "0",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "0": "0",
        "1": "4px",
        "2": "8px",
        "3": "12px",
        "4": "16px",
        "5": "24px",
        "6": "32px",
        "7": "40px",
        "8": "48px",
        "9": "64px",
        "10": "80px",
        "11": "96px",
        "12": "128px"
      },
      "borderRadius": {
        "none": "0",
        "sm": "4px",
        "md": "8px",
        "lg": "16px",
        "xl": "24px",
        "pill": "9999px"
      },
      "boxShadow": {
        "0": "none",
        "1": "0 1px 2px rgb(0 0 0 / 0.08), 0 1px 1px rgb(0 0 0 / 0.04)",
        "2": "0 4px 8px rgb(0 0 0 / 0.08), 0 2px 4px rgb(0 0 0 / 0.04)",
        "3": "0 12px 24px rgb(0 0 0 / 0.10), 0 4px 8px rgb(0 0 0 / 0.05)"
      },
      "transitionDuration": {
        "instant": "0ms",
        "fast": "120ms",
        "base": "200ms",
        "slow": "320ms",
        "deliberate": "500ms"
      },
      "transitionTimingFunction": {
        "standard": "cubic-bezier(0.2, 0, 0, 1)",
        "enter": "cubic-bezier(0, 0, 0, 1)",
        "exit": "cubic-bezier(0.3, 0, 1, 1)"
      },
      "screens": {
        "tablet": "768px",
        "desktop": "1024px",
        "wide": "1440px"
      }
    }
  }
};
