// Generated by style-guide-creator. Tailwind CSS v3 preset: presets: [require('./tailwind.preset.js')]
// Semantic colours read CSS variables, so also include tokens.css.
module.exports = {
  "theme": {
    "extend": {
      "colors": {
        "primary": {
          "DEFAULT": "#1d4e89",
          "50": "#f2f7ff",
          "100": "#e1eeff",
          "200": "#c3ddff",
          "300": "#99c4fc",
          "400": "#6ea4ea",
          "500": "#4c88d3",
          "600": "#356db2",
          "700": "#1d4e89",
          "800": "#184070",
          "900": "#0d2b50",
          "950": "#041832"
        },
        "secondary": {
          "DEFAULT": "#f36c5c",
          "50": "#fff4f2",
          "100": "#ffe6e2",
          "200": "#ffcdc5",
          "300": "#ffa699",
          "400": "#f36c5c",
          "500": "#e14b3d",
          "600": "#bd3126",
          "700": "#9b2018",
          "800": "#77130d",
          "900": "#550805",
          "950": "#360101"
        },
        "accent": {
          "DEFAULT": "#9ec8e7",
          "50": "#f1f8fd",
          "100": "#e0effb",
          "200": "#c4dff3",
          "300": "#9ec8e7",
          "400": "#72a8cf",
          "500": "#518db7",
          "600": "#397298",
          "700": "#295a7b",
          "800": "#1b445e",
          "900": "#0f2e42",
          "950": "#051a29"
        },
        "neutral": {
          "50": "#f6f7f8",
          "100": "#ebedef",
          "200": "#d8dbde",
          "300": "#bdc1c6",
          "400": "#9da2a8",
          "500": "#81878d",
          "600": "#676c72",
          "700": "#52565b",
          "800": "#3d4044",
          "900": "#292c2f",
          "950": "#0c1015"
        },
        "success": {
          "50": "#eefbf0",
          "100": "#dbf5df",
          "200": "#bae9c2",
          "300": "#8bd69a",
          "400": "#55ba70",
          "500": "#20a04e",
          "600": "#00823a",
          "700": "#00672c",
          "800": "#004e20",
          "900": "#003614",
          "950": "#001f08"
        },
        "warning": {
          "50": "#fff5e9",
          "100": "#fdead0",
          "200": "#f7d5a6",
          "300": "#ebb66a",
          "400": "#d59219",
          "500": "#b37900",
          "600": "#916100",
          "700": "#744c00",
          "800": "#573900",
          "900": "#3d2600",
          "950": "#241500"
        },
        "error": {
          "50": "#fff4f2",
          "100": "#ffe6e3",
          "200": "#ffcdc6",
          "300": "#ffa69b",
          "400": "#ee7b6f",
          "500": "#d5584f",
          "600": "#b33f38",
          "700": "#922e28",
          "800": "#701f1b",
          "900": "#50120f",
          "950": "#320605"
        },
        "info": {
          "50": "#f1f8ff",
          "100": "#e0efff",
          "200": "#c0deff",
          "300": "#8fc6ff",
          "400": "#53a6f7",
          "500": "#2389e2",
          "600": "#006ebe",
          "700": "#005798",
          "800": "#004174",
          "900": "#002c52",
          "950": "#001932"
        },
        "text-default": "var(--text-default)",
        "text-muted": "var(--text-muted)",
        "text-inverse": "var(--text-inverse)",
        "text-link": "var(--text-link)",
        "text-on-brand": "var(--text-on-brand)",
        "surface-default": "var(--surface-default)",
        "surface-subtle": "var(--surface-subtle)",
        "surface-inverse": "var(--surface-inverse)",
        "surface-brand": "var(--surface-brand)",
        "border-subtle": "var(--border-subtle)",
        "border-strong": "var(--border-strong)",
        "focus": "var(--focus)",
        "focus-on-brand": "var(--focus-on-brand)",
        "focus-on-primary": "var(--focus-on-primary)",
        "focus-on-secondary": "var(--focus-on-secondary)",
        "focus-on-accent": "var(--focus-on-accent)",
        "success-fg": "var(--success-fg)",
        "success-bg": "var(--success-bg)",
        "success-border": "var(--success-border)",
        "warning-fg": "var(--warning-fg)",
        "warning-bg": "var(--warning-bg)",
        "warning-border": "var(--warning-border)",
        "error-fg": "var(--error-fg)",
        "error-bg": "var(--error-bg)",
        "error-border": "var(--error-border)",
        "info-fg": "var(--info-fg)",
        "info-bg": "var(--info-bg)",
        "info-border": "var(--info-border)"
      },
      "fontFamily": {
        "display": [
          "'Nunito', system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif"
        ],
        "body": [
          "'Atkinson Hyperlegible Next', system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif"
        ],
        "mono": [
          "'JetBrains Mono', ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"
        ]
      },
      "fontSize": {
        "display": [
          "3.75rem",
          {
            "lineHeight": "1.1",
            "letterSpacing": "-0.02em",
            "fontWeight": "700"
          }
        ],
        "h1": [
          "3rem",
          {
            "lineHeight": "1.15",
            "letterSpacing": "-0.015em",
            "fontWeight": "700"
          }
        ],
        "h2": [
          "2.25rem",
          {
            "lineHeight": "1.2",
            "letterSpacing": "-0.01em",
            "fontWeight": "700"
          }
        ],
        "h3": [
          "1.75rem",
          {
            "lineHeight": "1.25",
            "letterSpacing": "0",
            "fontWeight": "600"
          }
        ],
        "h4": [
          "1.375rem",
          {
            "lineHeight": "1.3",
            "letterSpacing": "0",
            "fontWeight": "600"
          }
        ],
        "body-lg": [
          "1.25rem",
          {
            "lineHeight": "1.5",
            "letterSpacing": "0",
            "fontWeight": "400"
          }
        ],
        "body": [
          "1rem",
          {
            "lineHeight": "1.5",
            "letterSpacing": "0",
            "fontWeight": "400"
          }
        ],
        "small": [
          "0.875rem",
          {
            "lineHeight": "1.5",
            "letterSpacing": "0.01em",
            "fontWeight": "400"
          }
        ],
        "label": [
          "0.875rem",
          {
            "lineHeight": "1.4",
            "letterSpacing": "0.02em",
            "fontWeight": "600"
          }
        ],
        "code": [
          "0.9375rem",
          {
            "lineHeight": "1.5",
            "letterSpacing": "0",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "0": "0",
        "1": "4px",
        "2": "8px",
        "3": "12px",
        "4": "16px",
        "5": "24px",
        "6": "32px",
        "7": "40px",
        "8": "48px",
        "9": "64px",
        "10": "80px",
        "11": "96px",
        "12": "128px"
      },
      "borderRadius": {
        "none": "0",
        "sm": "6px",
        "md": "12px",
        "lg": "16px",
        "xl": "28px",
        "pill": "9999px"
      },
      "boxShadow": {
        "0": "none",
        "1": "0 1px 2px rgb(0 0 0 / 0.08), 0 1px 1px rgb(0 0 0 / 0.04)",
        "2": "0 4px 8px rgb(0 0 0 / 0.08), 0 2px 4px rgb(0 0 0 / 0.04)",
        "3": "0 12px 24px rgb(0 0 0 / 0.10), 0 4px 8px rgb(0 0 0 / 0.05)"
      },
      "transitionDuration": {
        "instant": "0ms",
        "fast": "120ms",
        "base": "200ms",
        "slow": "320ms",
        "deliberate": "500ms"
      },
      "transitionTimingFunction": {
        "standard": "cubic-bezier(0.2, 0, 0, 1)",
        "enter": "cubic-bezier(0, 0, 0, 1)",
        "exit": "cubic-bezier(0.3, 0, 1, 1)"
      },
      "screens": {
        "tablet": "768px",
        "desktop": "1024px",
        "wide": "1440px"
      }
    }
  }
};
