#!/usr/bin/env python3
"""Render the style guide from brand.json + content/*.md + assets/manifest.json.

Outputs at the guide root:
  style-guide.html   accessible, responsive, light/dark, print-ready single page
  style-guide.md     the same content as portable Markdown
  style-guide.pdf    only with --pdf and a headless Chrome/Chromium/Edge available

Chapter Markdown supports headings, paragraphs, lists, tables, blockquotes, code,
links, images, and callouts (a blockquote starting with **Do**, **Don't**, **Note**
or **Accessibility**). Lines containing only a placeholder such as {{color.pairings}}
are replaced with tables and galleries generated from the data.

Usage:
    render_guide.py path/to/brand.json [--pdf]
"""

from __future__ import annotations

import argparse
import html
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import brandlib as bl  # noqa: E402
import generate_tokens  # noqa: E402
from guide_spec import CHAPTER_STEMS  # noqa: E402

PLATFORMS_FILE = HERE.parent.parent / "social-media-kit" / "references" / "social-platforms.json"


# ============================================================================
# Data blocks: each placeholder returns a list of blocks rendered to HTML or MD
# ============================================================================

class Data:
    def __init__(self, brand_path: Path):
        self.root = brand_path.parent
        self.brand = json.loads(brand_path.read_text())
        mf = self.root / "assets" / "manifest.json"
        self.manifest = json.loads(mf.read_text()) if mf.exists() else {"files": [], "warnings": []}
        self.platforms = json.loads(PLATFORMS_FILE.read_text())
        self.sem = generate_tokens.semantic_aliases(self.brand)

    def files(self, prefix: str, suffix: tuple = (".png", ".svg")):
        return [f for f in self.manifest["files"] if f["path"].startswith(prefix) and f["path"].endswith(suffix)]


def _ratio_cell(ratio, required=None):
    ok = ratio >= (required or 4.5)
    return f"{ratio:.2f}:1 — {'Pass ✓' if ok else 'Fail ✗'}" if required is not None else f"{ratio:.2f}:1 ({bl.rating_label(ratio)})"


def chip(hex_value, label=None):
    return {"swatch": hex_value, "text": label or hex_value}


def ph_meta_table(d: Data):
    m = d.brand["meta"]
    rows = [["Organisation", m.get("name", "")], ["Guide version", m.get("version", "")],
            ["Last updated", m.get("lastUpdated", "")], ["Brand owner", m.get("owner", "")],
            ["Contact", m.get("contact", "")], ["Accessibility standard", m.get("accessibilityTarget", "")],
            ["Language and spelling", m.get("locale", "")], ["Review cadence", m.get("reviewCadence", "")]]
    blocks = [{"t": "table", "caption": "About this guide", "head": ["Item", "Detail"], "rows": rows}]
    if m.get("assumptions"):
        blocks.append({"t": "p", "text": "**Assumptions to confirm:**"})
        blocks.append({"t": "list", "items": m["assumptions"]})
    return blocks


def ph_logo_variants(d: Data):
    items = []
    files = [f for f in d.files("assets/logo/") if "/backgrounds/" not in f["path"]]
    pngs = {f["path"] for f in files if f["path"].endswith(".png")}
    for f in files:
        if f["path"].endswith(".svg") and f["path"][:-4] + ".png" in pngs:
            continue  # Show the PNG preview; the SVG is listed in downloads.
        bg = d.sem["light"]["surface-inverse"] if "mono-light" in f["path"] else "#ffffff"
        items.append({"src": f["path"], "alt": f.get("alt", ""), "caption": f["purpose"], "bg": bg})
    if not items:
        items.append({"src": d.brand["logo"]["master"], "alt": d.brand["logo"].get("altText", ""), "caption": "Primary logo", "bg": "#ffffff"})
    return [{"t": "gallery", "items": items}]


def ph_logo_specs(d: Data):
    lg = d.brand["logo"]
    ms = lg.get("minSize", {})
    rows = [
        ["Logo type", lg.get("type") or "—"],
        ["Clear space", lg.get("clearSpace", {}).get("rule", "")],
        ["Minimum size (screen)", f"{ms.get('digitalPx', '—')} px wide"],
        ["Minimum size (print)", f"{ms.get('printMm', '—')} mm wide"],
        ["Symbol minimum size", f"{ms.get('symbolDigitalPx', '—')} px / {ms.get('symbolPrintMm', '—')} mm"],
        ["Proportions", f"{lg.get('aspectRatio', '—')} : 1 (width : height), {lg.get('orientation', '')}"],
        ["Alt text", f"“{lg.get('altText', '')}”"],
    ]
    return [{"t": "table", "caption": "Logo specifications", "head": ["Rule", "Specification"], "rows": rows}]


def ph_logo_backgrounds(d: Data):
    tests = d.manifest.get("backgroundTests", [])
    if not tests:
        return [{"t": "p", "text": "_Background tests are generated by make_assets.py (requires Pillow)._"}]
    items = [{"src": t["file"], "alt": f"Logo on {t['background']} background ({t['hex']})",
              "caption": f"On {t['background']} ({t['hex']}): use **{t['recommendedVariant']}** ({t['contrast']}:1). "
                         f"Full colour {'allowed as an approved exception' if t.get('approvedException') else 'allowed' if t['fullColourAllowed'] else 'not allowed'} ({t['fullColourContrast']}:1)."}
             for t in tests]
    rows = [[chip(t["hex"], t["background"]), t["recommendedVariant"], f"{t['contrast']}:1",
             ("Yes, approved exception" if t.get("approvedException") else "Yes" if t["fullColourAllowed"] else "No") + f" ({t['fullColourContrast']}:1)"] for t in tests]
    return [{"t": "gallery", "items": items},
            {"t": "table", "caption": "Which logo version to use on each background (minimum 3:1)",
             "head": ["Background", "Use this version", "Contrast", "Full colour allowed?"], "rows": rows}]


def ph_color_brand(d: Data):
    items = []
    for c in d.brand["color"]["brand"]:
        f = bl.colour_formats(c["hex"])
        on_white = bl.contrast_ratio(c["hex"], "#ffffff")
        dark_text = d.brand["color"]["neutral"]["scale"]["950"]
        white_on = bl.contrast_ratio("#ffffff", c["hex"])
        dark_on = bl.contrast_ratio(dark_text, c["hex"])
        best_label, best = ("White", white_on) if white_on >= dark_on else ("Dark", dark_on)
        text_step = c.get("accessible", {}).get("textOnLight")
        if on_white >= 4.5:
            text_line = "As text on white: use as is"
        elif text_step:
            text_line = f"As text on white: use {c['id']}-{text_step['step']} {text_step['hex']}"
        else:
            text_line = "As text on white: not suitable"
        items.append({
            "name": c["name"], "hex": c["hex"], "role": c.get("role", ""),
            "fg": "#ffffff" if white_on >= dark_on else dark_text,
            "lines": [f"HEX {f['hex']}", f["rgb"].upper().replace("RGB", "RGB "), f["hsl"].upper().replace("HSL", "HSL "), f["oklch"],
                      f"CMYK {f['cmyk']} (verify)", f"Pantone: {c.get('pantone') or 'to be matched'}",
                      f"On white: {_ratio_cell(on_white)}", f"{best_label} text on it: {_ratio_cell(best)}", text_line],
        })
    return [{"t": "swatches", "items": items}]


def ph_color_proportions(d: Data):
    props = d.brand["color"].get("proportions", {})
    lookup = {c["id"]: c for c in d.brand["color"]["brand"]}
    items = []
    for k, v in props.items():
        hx = lookup[k]["hex"] if k in lookup else d.brand["color"]["neutral"]["scale"]["100"]
        name = lookup[k]["name"] if k in lookup else "Neutrals and white"
        items.append({"label": f"{name} {v}%", "hex": hx, "pct": v})
    return [{"t": "bar", "items": items, "caption": "Approximate share of colour across a typical layout"}]


def ph_color_scales(d: Data):
    blocks = []
    groups = [(c["name"], c["id"], c["scale"]) for c in d.brand["color"]["brand"]]
    groups.append(("Neutral", "neutral", d.brand["color"]["neutral"]["scale"]))
    for name, cid, scale in groups:
        rows = []
        for step, hx in scale.items():
            w, k = bl.contrast_ratio(hx, "#ffffff"), bl.contrast_ratio(hx, "#000000")
            rows.append([chip(hx, f"{cid}-{step}"), hx, _ratio_cell(w), _ratio_cell(k),
                         "White" if bl.contrast_ratio("#ffffff", hx) >= 4.5 else "Dark" if k >= 4.5 else "Large text only"])
        blocks.append({"t": "table", "caption": f"{name} tonal scale",
                       "head": ["Token", "HEX", "Contrast with white", "Contrast with black", "Text colour on it"], "rows": rows})
    return blocks


def ph_color_semantic(d: Data):
    rows = []
    for s in d.brand["color"].get("semantic", []):
        t = s["tokens"]
        rows.append([s["id"].title(), chip(t["fg"]["hex"]) if t.get("fg") else "—", chip(t["bg"]["hex"]),
                     chip(t["border"]["hex"]) if t.get("border") else "—", chip(t["solid"]["hex"]) if t.get("solid") else "—"])
    return [{"t": "table", "caption": "State colours (always pair with an icon and text)",
             "head": ["State", "Text / icon", "Background", "Border", "Solid (white text)"], "rows": rows}]


def ph_color_pairings(d: Data):
    rows = []
    for p in d.brand["color"].get("pairings", []):
        ratio = bl.contrast_ratio(p["fg"], p["bg"])  # Recompute: never trust stored values.
        req = bl.THRESHOLDS.get(p["use"], 4.5)
        rows.append([{"sample": (p["fg"], p["bg"]), "text": "Aa"}, p["label"], f"{p['fgToken']} {p['fg']}",
                     f"{p['bgToken']} {p['bg']}", f"{ratio:.2f}:1",
                     {"body": "Any text (4.5:1)", "large": "Large text and UI only (3:1)", "ui": "UI and graphics (3:1)",
                      "decorative": "Decorative only"}.get(p["use"], p["use"]),
                     "Pass ✓" if ratio >= req else "Fail ✗"])
    return [{"t": "table", "caption": "Approved colour pairings and WCAG 2.2 contrast",
             "head": ["Sample", "Use", "Foreground", "Background", "Ratio", "Approved for", "Result"], "rows": rows}]


def ph_color_cvd(d: Data):
    colours = [(c["name"], c["hex"]) for c in d.brand["color"]["brand"]]
    colours += [(s["id"].title(), s["tokens"]["fg"]["hex"]) for s in d.brand["color"].get("semantic", []) if s["tokens"].get("fg")]
    rows = [[n, chip(h)] + [chip(bl.simulate_cvd(h, k)) for k in bl.CVD_KINDS] for n, h in colours]
    blocks = [{"t": "table", "caption": "How key colours appear with colour-vision deficiencies (simulated)",
               "head": ["Colour", "Typical vision", "Protanopia", "Deuteranopia", "Tritanopia", "Achromatopsia"], "rows": rows}]
    issues = d.brand["color"].get("cvd", [])
    if issues:
        blocks.append({"t": "p", "text": "**Pairs that may be confused** — never use these together as the only way to tell things apart:"})
        blocks.append({"t": "list", "items": [f"{i['pair'][0]} and {i['pair'][1]} ({i['vision']})" for i in issues]})
    return blocks


def ph_type_families(d: Data):
    rows = [[f["role"].title(), f["name"], ", ".join(map(str, f.get("weights", []))), f.get("fallback", ""),
             f.get("source", "") or "—", f.get("license", "") or "Confirm licence"] for f in d.brand["typography"]["families"]]
    return [{"t": "table", "caption": "Typefaces", "head": ["Role", "Typeface", "Weights", "Fallback stack", "Source", "Licence"], "rows": rows}]


def ph_type_scale(d: Data):
    fams = {f["role"]: f for f in d.brand["typography"]["families"]}
    items = []
    for t in d.brand["typography"]["scale"]:
        fam = fams.get(t["family"], {})
        items.append({**t, "css": f"'{fam.get('name', '')}', {fam.get('fallback', 'sans-serif')}",
                      "meta": f"{t['token']} — {t['sizePx']}px / {t['sizePx'] / 16:g}rem, line height {t['lineHeight']}, weight {t['weight']}, tracking {t['letterSpacing']}. {t.get('usage', '')}"})
    rows = [[t["token"], f"{t['sizePx']}px ({t['sizePx'] / 16:g}rem)", str(t["lineHeight"]), str(t["weight"]), t["letterSpacing"], t["family"], t.get("usage", "")]
            for t in d.brand["typography"]["scale"]]
    return [{"t": "specimen", "items": items},
            {"t": "table", "caption": "Type scale", "head": ["Token", "Size", "Line height", "Weight", "Tracking", "Family", "Use"], "rows": rows}]


def ph_spacing(d: Data):
    sc = d.brand["spacing"]["scale"]
    return [{"t": "spacing", "items": [{"token": f"space-{k}", "px": v} for k, v in sc.items()]},
            {"t": "table", "caption": f"Spacing scale (base unit {d.brand['spacing'].get('basePx', 4)}px)",
             "head": ["Token", "Pixels", "rem"], "rows": [[f"space-{k}", f"{v}px", f"{v / 16:g}rem"] for k, v in sc.items()]}]


def ph_grid(d: Data):
    g = d.brand.get("grid", {})
    rows = [[b["id"].title(), f"{b['minPx']}px+", str(b["columns"]), f"{b['gutterPx']}px", f"{b['marginPx']}px"] for b in g.get("breakpoints", [])]
    return [{"t": "table", "caption": f"Layout grid (maximum content width {g.get('maxContentWidthPx', '—')}px)",
             "head": ["Breakpoint", "Viewport", "Columns", "Gutter", "Margin"], "rows": rows}]


def ph_radius(d: Data):
    return [{"t": "table", "caption": "Corner radius", "head": ["Token", "Value", "Typical use"],
             "rows": [[f"radius-{k}", "fully rounded" if v >= 999 else f"{v}px",
                       {"none": "Tables, full-bleed images", "sm": "Inputs, tags", "md": "Buttons, cards", "lg": "Panels, modals",
                        "xl": "Feature cards, media", "pill": "Pills, avatars, toggles"}.get(k, "")] for k, v in d.brand.get("radius", {}).items()]}]


def ph_elevation(d: Data):
    return [{"t": "table", "caption": "Elevation (shadows)", "head": ["Token", "Value", "Use"],
             "rows": [[f"shadow-{k}", v, ["Flat surfaces", "Cards, raised buttons", "Dropdowns, popovers", "Modals, dialogs"][min(int(k), 3)] if k.isdigit() else ""]
                      for k, v in d.brand.get("elevation", {}).items()]}]


def ph_motion(d: Data):
    m = d.brand.get("motion", {})
    rows = [[f"duration-{k}", v] for k, v in m.get("durations", {}).items()] + [[f"ease-{k}", v] for k, v in m.get("easing", {}).items()]
    return [{"t": "table", "caption": "Motion tokens", "head": ["Token", "Value"], "rows": rows},
            {"t": "p", "text": f"**Reduced motion:** {m.get('reducedMotion', '')}"}]


def ph_focus(d: Data):
    f = d.brand.get("focus", {})
    light, dark = f.get("colorOnLight", "#000000"), f.get("colorOnDark", "#ffffff")
    rows = [["Focus colour on light surfaces", chip(light), _ratio_cell(bl.contrast_ratio(light, "#ffffff"), 3.0)],
            ["Focus colour on dark surfaces", chip(dark), _ratio_cell(bl.contrast_ratio(dark, d.sem["dark"]["surface-default"]), 3.0)],
            *[[f"Focus colour inside {next((c['name'] for c in d.brand['color']['brand'] if c['id'] == cid), cid)} sections",
               chip(spec["focus"]), _ratio_cell(spec["ratio"], 3.0)] for cid, spec in f.get("onBrand", {}).items()],
            ["Outline width", f"{f.get('widthPx', 3)}px", "At least 2px (WCAG 2.4.13 guidance)"],
            ["Offset from element", f"{f.get('offsetPx', 2)}px", ""]]
    primary_id = d.brand["color"]["brand"][0]["id"]
    on_brand = f.get("onBrand", {}).get(primary_id, {}).get("focus", "#ffffff")
    return [{"t": "focus", "light": light, "dark": dark, "brand": on_brand, "width": f.get("widthPx", 3), "offset": f.get("offsetPx", 2)},
            {"t": "table", "caption": "Focus indicator", "head": ["Property", "Value", "Check"], "rows": rows}]


def ph_favicons(d: Data):
    items = [{"src": f["path"], "alt": f["purpose"], "caption": f["purpose"], "bg": "#ffffff"}
             for f in d.files("assets/favicons/", (".png",)) if any(s in f["path"] for s in ("icon-192", "apple-touch", "maskable", "icon-48"))]
    blocks = [{"t": "gallery", "items": items, "small": True}] if items else []
    snippet = d.root / "assets" / "favicons" / "head-snippet.html"
    if snippet.exists():
        blocks.append({"t": "code", "lang": "html", "text": snippet.read_text()})
    return blocks


def ph_social_specs(d: Data):
    chosen = d.brand.get("social", {}).get("platforms") or [p["id"] for p in d.platforms["platforms"]]
    rows, access = [], []
    for p in d.platforms["platforms"]:
        if p["id"] not in chosen:
            continue
        for f in p["formats"]:
            sz = f.get("safeZone")
            safe = (f"inset T{sz['top']:.0%} R{sz['right']:.0%} B{sz['bottom']:.0%} L{sz['left']:.0%}" if sz else
                    "inside circular crop" if f.get("displayShape") == "circle" else "8% margin")
            rows.append([p["name"], f["label"], f"{f['width']} × {f['height']} px", _aspect(f["width"], f["height"]), safe, f.get("note", "")])
        access.append([p["name"], p.get("altText", ""), p.get("captions", "")])
    return [{"t": "p", "text": f"_Specifications last reviewed {d.platforms['lastReviewed']}. {d.platforms['disclaimer']}_"},
            {"t": "table", "caption": "Image sizes by platform", "head": ["Platform", "Format", "Size", "Ratio", "Safe zone", "Notes"], "rows": rows},
            {"t": "table", "caption": "Accessibility features by platform", "head": ["Platform", "Image descriptions (alt text)", "Video captions"], "rows": access}]


def _aspect(w, h):
    from math import gcd
    g = gcd(w, h)
    a, b = w // g, h // g
    return f"{a}:{b}" if a <= 32 and b <= 32 else f"{w / h:.2f}:1"


def ph_social_assets(d: Data):
    blocks = []
    by_platform: dict = {}
    for f in d.files("assets/social/", (".png",)):
        by_platform.setdefault(f["path"].split("/")[2], []).append(f)
    names = {p["id"]: p["name"] for p in d.platforms["platforms"]}
    for pid, files in by_platform.items():
        blocks.append({"t": "h", "text": names.get(pid, pid)})
        blocks.append({"t": "gallery", "items": [{"src": f["path"], "alt": f.get("alt", ""), "caption": f["purpose"] + (f" — {f['note']}" if f.get("note") else ""), "bg": "#ffffff"} for f in files], "small": True})
    if not blocks:
        templates = d.files("assets/social/", (".svg",))
        blocks.append({"t": "p", "text": f"{len(templates)} editable SVG templates are in `assets/social/`. Install Pillow and re-run make_assets.py for PNG previews."})
    blocks.append({"t": "p", "text": "Each format also has an editable SVG template (with a hideable `guides` layer) and a `-guides.svg` safe-zone overlay in the same folder."})
    return blocks


def ph_downloads(d: Data):
    groups: dict = {}
    for f in d.manifest["files"]:
        parts = f["path"].split("/")
        key = parts[1] if len(parts) > 2 else "other"
        groups.setdefault(key, []).append(f)
    blocks = []
    labels = {"logo": "Logo files", "favicons": "Favicons and app icons", "social": "Social media kit", "source": "Source artwork"}
    for key, files in groups.items():
        blocks.append({"t": "h", "text": labels.get(key, key.title())})
        shown = files if len(files) <= 30 else files[:30]
        items = [f"[{f['path'].split('/')[-1]}]({f['path']}) — {f['purpose']}" for f in shown]
        if len(files) > 30:
            items.append(f"…and {len(files) - 30} more in `assets/{key}/`")
        blocks.append({"t": "list", "items": items})
    tok = d.root / "tokens"
    if tok.exists():
        blocks.append({"t": "h", "text": "Design tokens"})
        blocks.append({"t": "list", "items": [f"[{p.name}](tokens/{p.name})" for p in sorted(tok.iterdir())]})
    return blocks


PLACEHOLDER_FUNCS = {
    "meta.table": ph_meta_table, "logo.variants": ph_logo_variants, "logo.specs": ph_logo_specs,
    "logo.backgrounds": ph_logo_backgrounds, "color.brand": ph_color_brand, "color.proportions": ph_color_proportions,
    "color.scales": ph_color_scales, "color.semantic": ph_color_semantic, "color.pairings": ph_color_pairings,
    "color.cvd": ph_color_cvd, "type.families": ph_type_families, "type.scale": ph_type_scale,
    "spacing.scale": ph_spacing, "grid": ph_grid, "radius": ph_radius, "elevation": ph_elevation,
    "motion": ph_motion, "focus": ph_focus, "favicons": ph_favicons, "social.specs": ph_social_specs,
    "social.assets": ph_social_assets, "downloads": ph_downloads,
}


# ============================================================================
# Markdown -> HTML
# ============================================================================

def inline(text: str) -> str:
    codes: list[str] = []

    def keep(m):
        codes.append(f"<code>{html.escape(m.group(1))}</code>")
        return f"\x00{len(codes) - 1}\x00"

    text = re.sub(r"`([^`]+)`", keep, text)
    text = html.escape(text, quote=False)
    text = re.sub(r"!\[([^\]]*)\]\(([^)\s]+)(?:\s+&quot;[^&]*&quot;)?\)",
                  lambda m: f'<img src="{html.escape(m.group(2), quote=True)}" alt="{html.escape(m.group(1), quote=True)}" loading="lazy">', text)
    text = re.sub(r"\[([^\]]+)\]\(([^)\s]+)\)", lambda m: f'<a href="{html.escape(m.group(2), quote=True)}">{m.group(1)}</a>', text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"(?<![\w*])\*([^*\n]+)\*(?![\w*])", r"<em>\1</em>", text)
    text = re.sub(r"(?<![\w_])_([^_\n]+)_(?![\w_])", r"<em>\1</em>", text)
    return re.sub(r"\x00(\d+)\x00", lambda m: codes[int(m.group(1))], text)


class Slugger:
    def __init__(self):
        self.seen: dict = {}

    def __call__(self, text):
        base = bl.slugify(re.sub(r"<[^>]+>", "", text)) or "section"
        n = self.seen.get(base, 0)
        self.seen[base] = n + 1
        return base if n == 0 else f"{base}-{n}"


def md_to_html(md: str, slug: Slugger, render_ph, shift: int = 1, toc: list | None = None) -> str:
    lines = md.splitlines()
    out: list[str] = []
    para: list[str] = []
    i = 0
    current = shift + 1  # Level of the most recent heading; generated sub-headings go one below it.
    last_heading = ""
    pending_caption = None

    def flush():
        if para:
            out.append(f"<p>{inline(' '.join(s.strip() for s in para))}</p>")
            para.clear()

    while i < len(lines):
        line = lines[i]
        s = line.strip()
        if s.startswith("<!--"):
            flush()
            while "-->" not in lines[i]:
                i += 1
            i += 1
            continue
        if not s:
            flush()
            i += 1
            continue
        m = re.fullmatch(r"\{\{([\w.]+)\}\}", s)
        if m:
            flush()
            out.append(render_ph(m.group(1), current))
            i += 1
            continue
        if s.startswith("```"):
            flush()
            lang = s[3:].strip()
            code = []
            i += 1
            while i < len(lines) and not lines[i].strip().startswith("```"):
                code.append(lines[i])
                i += 1
            i += 1
            out.append(f'<pre><code{f" class=language-{html.escape(lang)}" if lang else ""}>{html.escape(chr(10).join(code))}</code></pre>')
            continue
        m = re.match(r"^(#{1,6})\s+(.*)$", s)
        if m:
            flush()
            level = min(6, len(m.group(1)) + shift)
            current = level
            text = inline(m.group(2).strip())
            last_heading = re.sub(r"<[^>]+>", "", text)
            hid = slug(text)
            if toc is not None and level <= 3:
                toc.append((level, hid, re.sub(r"<[^>]+>", "", text)))
            out.append(f'<h{level} id="{hid}">{text}</h{level}>')
            i += 1
            continue
        if re.fullmatch(r"(-{3,}|\*{3,}|_{3,})", s):
            flush()
            out.append("<hr>")
            i += 1
            continue
        m = re.fullmatch(r"Table:\s*(.+)", s)
        if m and i + 1 < len(lines) and (lines[i + 1].strip().startswith("|") or (i + 2 < len(lines) and not lines[i + 1].strip() and lines[i + 2].strip().startswith("|"))):
            flush()
            pending_caption = m.group(1).strip()
            i += 1
            continue
        if s.startswith("|") and i + 1 < len(lines) and re.fullmatch(r"\|?\s*:?-{2,}:?\s*(\|\s*:?-{2,}:?\s*)*\|?", lines[i + 1].strip()):
            flush()
            head = [c.strip() for c in s.strip("|").split("|")]
            i += 2
            rows = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                rows.append([c.strip() for c in lines[i].strip().strip("|").split("|")])
                i += 1
            if pending_caption:
                out.append(html_table(pending_caption, head, rows, md_cells=True))
            else:  # Every table gets a caption; fall back to the section heading, shown to screen readers only.
                out.append(html_table(last_heading or head[0], head, rows, md_cells=True, hidden_caption=True))
            pending_caption = None
            continue
        if s.startswith(">"):
            flush()
            quote = []
            while i < len(lines) and lines[i].strip().startswith(">"):
                quote.append(re.sub(r"^\s*>\s?", "", lines[i]))
                i += 1
            inner = md_to_html("\n".join(quote), slug, render_ph, shift=shift)
            kind = re.match(r"\s*\*\*(Do|Don['’]t|Note|Accessibility|Warning)\b", quote[0] if quote else "")
            cls = {"do": "do", "don't": "dont", "don’t": "dont", "note": "note", "accessibility": "a11y", "warning": "warn"}.get(kind.group(1).lower(), "note") if kind else None
            out.append(f'<div class="callout callout-{cls}" role="note">{inner}</div>' if cls else f"<blockquote>{inner}</blockquote>")
            continue
        if re.match(r"^\s*([-*+]|\d+[.)])\s+", line):
            flush()
            block = []
            while i < len(lines) and (re.match(r"^\s*([-*+]|\d+[.)])\s+", lines[i]) or (lines[i].startswith("  ") and lines[i].strip())):
                block.append(lines[i])
                i += 1
            out.append(html_list(block))
            continue
        if s.startswith("<") and s.endswith(">"):
            flush()
            out.append(s)
            i += 1
            continue
        para.append(line)
        i += 1
    flush()
    return "\n".join(out)


def html_list(block: list[str]) -> str:
    """Render a list block; items indented by 2+ spaces nest inside the previous item."""
    parsed: list[list] = []
    for line in block:
        m = re.match(r"^(\s*)([-*+]|\d+[.)])\s+(.*)$", line)
        if not m:
            parsed[-1][2] += " " + line.strip()
            continue
        parsed.append([len(m.group(1)) // 2, "ol" if m.group(2)[0].isdigit() else "ul", m.group(3)])
    out, stack = [], []
    for indent, tag, text in parsed:
        while stack and stack[-1][0] > indent:
            out.append(f"</li></{stack.pop()[1]}>")
        if stack and stack[-1][0] == indent and stack[-1][1] != tag:
            out.append(f"</li></{stack.pop()[1]}><{tag}>")
            stack.append((indent, tag))
        elif stack and stack[-1][0] == indent:
            out.append("</li>")
        else:
            out.append(f"<{tag}>")
            stack.append((indent, tag))
        out.append(f"<li>{inline(text)}")
    while stack:
        out.append(f"</li></{stack.pop()[1]}>")
    return "".join(out)


def cell_html(c, md_cells=False) -> str:
    if isinstance(c, dict):
        if "sample" in c:
            fg, bg = c["sample"]
            return f'<span class="sample" style="color:{fg};background:{bg}">{html.escape(c["text"])}</span>'
        return f'<span class="chip" style="background:{c["swatch"]}" aria-hidden="true"></span> <code>{html.escape(c["text"])}</code>'
    return inline(str(c))


def html_table(caption, head, rows, md_cells=False, hidden_caption=False) -> str:
    cls = ' class="visually-hidden"' if hidden_caption else ""
    cap = f"<caption{cls}>{inline(caption)}</caption>" if caption else ""
    th = "".join(f'<th scope="col">{inline(h)}</th>' for h in head)
    body = []
    for r in rows:
        cells = [f'<th scope="row">{cell_html(r[0])}</th>'] + [f"<td>{cell_html(c)}</td>" for c in r[1:]]
        body.append("<tr>" + "".join(cells) + "</tr>")
    return f'<div class="table-wrap" data-label="{html.escape(caption or head[0], quote=True)}"><table>{cap}<thead><tr>{th}</tr></thead><tbody>{"".join(body)}</tbody></table></div>'


def blocks_html(blocks, slug: Slugger, level: int = 2) -> str:
    out = []
    sub = min(6, level + 1)
    for b in blocks:
        t = b["t"]
        if t == "p":
            out.append(f"<p>{inline(b['text'])}</p>")
        elif t == "h":
            out.append(f'<h{sub} id="{slug(b["text"])}">{html.escape(b["text"])}</h{sub}>')
        elif t == "list":
            out.append("<ul>" + "".join(f"<li>{inline(x)}</li>" for x in b["items"]) + "</ul>")
        elif t == "code":
            out.append(f"<pre><code>{html.escape(b['text'])}</code></pre>")
        elif t == "table":
            out.append(html_table(b.get("caption"), b["head"], b["rows"]))
        elif t == "gallery":
            figs = "".join(
                f'<div class="fig" style="--tile-bg:{it.get("bg", "#ffffff")}"><div class="tile"><img src="{html.escape(it["src"], quote=True)}" '
                f'alt="{html.escape(it.get("alt", ""), quote=True)}" loading="lazy"></div><p class="figcaption">{inline(it.get("caption", ""))}</p></div>'
                for it in b["items"])
            out.append(f'<div class="gallery{" gallery-sm" if b.get("small") else ""}">{figs}</div>')
        elif t == "swatches":
            cards = []
            for it in b["items"]:
                lines = "".join(f"<li>{inline(x)}</li>" for x in it["lines"] if x)
                cards.append(
                    f'<article class="swatch" aria-labelledby="sw-{it["hex"][1:]}"><div class="swatch-colour" style="background:{it["hex"]};color:{it["fg"]}">'
                    f'<span>{html.escape(it["role"].title())}</span></div><div class="swatch-body"><p class="swatch-name" id="sw-{it["hex"][1:]}">{html.escape(it["name"])}</p>'
                    f'<ul>{lines}</ul><button type="button" class="copy" data-copy="{it["hex"]}">Copy HEX <span class="visually-hidden">{html.escape(it["name"])} {it["hex"]}</span></button></div></article>')
            out.append(f'<div class="swatches">{"".join(cards)}</div>')
        elif t == "bar":
            segs = "".join(f'<div class="bar-seg" style="flex:{it["pct"]};background:{it["hex"]}" title="{html.escape(it["label"])}"></div>' for it in b["items"])
            legend = "".join(f'<li><span class="chip" style="background:{it["hex"]}" aria-hidden="true"></span> {html.escape(it["label"])}</li>' for it in b["items"])
            out.append(f'<div class="bar"><div class="bar-track" aria-hidden="true">{segs}</div><p class="figcaption">{html.escape(b["caption"])}</p><ul class="legend">{legend}</ul></div>')
        elif t == "specimen":
            rows = "".join(
                f'<div class="specimen-row"><p class="specimen-sample" style="font-family:{html.escape(it["css"], quote=True)};font-size:{it["sizePx"] / 16:g}rem;'
                f'line-height:{it["lineHeight"]};font-weight:{it["weight"]};letter-spacing:{it["letterSpacing"]}">'
                f'{"The quick brown fox jumps over the lazy dog" if it["sizePx"] < 30 else "Clear, confident, kind"}</p>'
                f'<p class="specimen-meta">{html.escape(it["meta"])}</p></div>' for it in b["items"])
            out.append(f'<div class="specimen">{rows}</div>')
        elif t == "spacing":
            rows = "".join(f'<li><span class="space-bar" style="width:{max(it["px"], 1)}px" aria-hidden="true"></span><code>{it["token"]}</code> {it["px"]}px</li>' for it in b["items"])
            out.append(f'<ul class="spacing">{rows}</ul>')
        elif t == "focus":
            out.append(
                f'<div class="focus-demo"><div class="focus-tile" style="background:#fff"><span class="fake-btn" style="outline:{b["width"]}px solid {b["light"]};outline-offset:{b["offset"]}px">Focused button</span></div>'
                f'<div class="focus-tile" style="background:var(--surface-inverse-fixed)"><span class="fake-btn dark" style="outline:{b["width"]}px solid {b["dark"]};outline-offset:{b["offset"]}px">Focused button</span></div>'
                f'<div class="focus-tile" style="background:var(--surface-brand-fixed)"><span class="fake-btn on-brand" style="outline:{b["width"]}px solid {b["brand"]};outline-offset:{b["offset"]}px">Focused button</span></div></div>')
    return "\n".join(out)


# ============================================================================
# Markdown output
# ============================================================================

def cell_md(c) -> str:
    if isinstance(c, dict):
        return c["text"] if "sample" in c else f"`{c['text']}`"
    return str(c).replace("|", "\\|").replace("\n", " ")


def blocks_md(blocks) -> str:
    out = []
    for b in blocks:
        t = b["t"]
        if t == "p":
            out.append(b["text"])
        elif t == "h":
            out.append(f"#### {b['text']}")
        elif t == "list":
            out.append("\n".join(f"- {x}" for x in b["items"]))
        elif t == "code":
            out.append(f"```html\n{b['text'].rstrip()}\n```")
        elif t == "table":
            lines = [f"**{b['caption']}**", ""] if b.get("caption") else []
            lines.append("| " + " | ".join(b["head"]) + " |")
            lines.append("|" + "---|" * len(b["head"]))
            lines += ["| " + " | ".join(cell_md(c) for c in r) + " |" for r in b["rows"]]
            out.append("\n".join(lines))
        elif t == "gallery":
            out.append("\n\n".join(f"![{it.get('alt', '')}]({it['src']})\n*{it.get('caption', '')}*" for it in b["items"]))
        elif t == "swatches":
            out.append("\n\n".join(f"**{it['name']}** ({it['role']})\n\n" + "\n".join(f"- {x}" for x in it["lines"] if x) for it in b["items"]))
        elif t == "bar":
            out.append(f"*{b['caption']}*\n\n" + "\n".join(f"- {it['label']}" for it in b["items"]))
        elif t == "specimen":
            out.append("\n".join(f"- {it['meta']}" for it in b["items"]))
        elif t == "spacing":
            continue  # The accompanying table covers it.
        elif t == "focus":
            out.append(f"Focus ring: {b['width']}px solid, {b['offset']}px offset; `{b['light']}` on light, `{b['dark']}` on dark surfaces.")
    return "\n\n".join(out)


# ============================================================================
# Page
# ============================================================================

def google_fonts_link(brand) -> str:
    fams = []
    for f in brand["typography"]["families"]:
        if "google" in (f.get("source") or "").lower() and f.get("name"):
            w = ";".join(str(x) for x in sorted(set(f.get("weights") or [400])))
            spec = f"family={f['name'].replace(' ', '+')}:wght@{w}"
            if spec not in fams:
                fams.append(spec)
    if not fams:
        return ""
    return ('<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>'
            f'<link rel="stylesheet" href="https://fonts.googleapis.com/css2?{"&".join(fams)}&display=swap">')


PAGE_CSS = """
*,*::before,*::after{box-sizing:border-box}
html{-webkit-text-size-adjust:100%;scroll-padding-top:1rem}
body{margin:0;background:var(--surface-default);color:var(--text-default);font-family:var(--font-body);font-size:1rem;line-height:1.6}
:root{--surface-inverse-fixed:%DARK%;--surface-brand-fixed:%BRAND%}
a{color:var(--text-link);text-underline-offset:.2em}
a:hover{text-decoration-thickness:2px}
:focus-visible{outline:var(--focus-width) solid var(--focus);outline-offset:var(--focus-offset)}
.skip-link{position:absolute;left:1rem;top:-10rem;background:var(--surface-default);color:var(--text-link);padding:.75rem 1rem;z-index:10;border:2px solid var(--focus)}
.skip-link:focus{top:1rem}
.visually-hidden{position:absolute!important;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap}
.site-header{background:var(--surface-subtle);border-bottom:1px solid var(--border-subtle);padding:2.5rem 1rem}
.site-header .inner,.layout{max-width:1200px;margin:0 auto}
.site-header img{max-height:72px;max-width:min(320px,80vw);display:block;margin-bottom:1.25rem}
.site-header h1{font-family:var(--font-display);font-size:clamp(2rem,5vw,3rem);line-height:1.1;margin:0 0 .5rem}
.site-header p{margin:0;color:var(--text-muted);overflow-wrap:anywhere}
.site-header .logo-dark{display:none}
@media screen and (prefers-color-scheme:dark){:root:not([data-theme="light"]) .site-header .logo-light{display:none}:root:not([data-theme="light"]) .site-header .logo-dark{display:block}}
[data-theme="dark"] .site-header .logo-light{display:none}[data-theme="dark"] .site-header .logo-dark{display:block}
body{overflow-wrap:break-word}
.layout{display:grid;grid-template-columns:minmax(0,1fr);gap:2rem;padding:2rem 1rem 4rem}
@media (min-width:1024px){.layout{grid-template-columns:240px minmax(0,1fr)}.toc{position:sticky;top:1rem;max-height:calc(100vh - 2rem);overflow:auto}}
.toc h2{font-size:.875rem;text-transform:uppercase;letter-spacing:.06em;color:var(--text-muted);margin:0 0 .5rem}
.toc ol{list-style:none;padding:0;margin:0}
.toc a{display:block;padding:.35rem .5rem;border-radius:6px;text-decoration:none;color:var(--text-default);min-height:24px}
.toc a:hover{background:var(--surface-subtle);text-decoration:underline}
main{min-width:0;max-width:72ch}
main section{padding-bottom:2.5rem;margin-bottom:2.5rem;border-bottom:1px solid var(--border-subtle)}
main h2{font-family:var(--font-display);font-size:clamp(1.75rem,3.5vw,2.25rem);line-height:1.2;margin:0 0 1rem}
main h3{font-family:var(--font-display);font-size:1.5rem;line-height:1.25;margin:2rem 0 .75rem}
main h4{font-size:1.125rem;margin:1.5rem 0 .5rem}
main h5,main h6{font-size:1rem;margin:1.25rem 0 .5rem}
p,li{max-width:72ch}
code{font-family:var(--font-mono);font-size:.9em;background:var(--surface-subtle);padding:.1em .3em;border-radius:4px}
pre{background:var(--surface-subtle);border:1px solid var(--border-subtle);padding:1rem;overflow:auto;border-radius:8px}
pre code{background:none;padding:0}
img{max-width:100%;height:auto}
.table-wrap{overflow-x:auto;margin:1rem 0 1.5rem;max-width:100%}
.table-wrap:focus-visible{outline-offset:2px}
table{border-collapse:collapse;width:100%;font-size:.9375rem}
caption{text-align:left;font-weight:700;padding:.5rem 0}
th,td{border-bottom:1px solid var(--border-subtle);padding:.5rem .75rem;text-align:left;vertical-align:top}
thead th{border-bottom:2px solid var(--border-strong)}
tbody th{font-weight:600}
.chip{display:inline-block;width:1.1em;height:1.1em;border-radius:4px;vertical-align:-.15em;border:1px solid var(--border-strong)}
.sample{display:inline-block;padding:.2rem .6rem;border-radius:6px;font-weight:700;border:1px solid var(--border-subtle)}
.gallery{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:1rem;margin:1rem 0 1.5rem;max-width:none}
.gallery-sm{grid-template-columns:repeat(auto-fill,minmax(180px,1fr))}
figure,.fig{margin:0}
.tile{background:var(--tile-bg);border:1px solid var(--border-subtle);border-radius:8px;padding:1rem;display:flex;align-items:center;justify-content:center;min-height:140px}
.tile img{max-height:220px;object-fit:contain}
figcaption,.figcaption{font-size:.875rem;color:var(--text-muted);margin:.4rem 0 0}
.swatches{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:1rem;margin:1rem 0}
.swatch{border:1px solid var(--border-subtle);border-radius:12px;overflow:hidden;background:var(--surface-default)}
.swatch-colour{height:120px;padding:1rem;display:flex;align-items:flex-end;font-weight:700}
.swatch-body{padding:1rem}
.swatch-name{margin:0 0 .5rem;font-weight:700;font-size:1.125rem}
.swatch-body ul{list-style:none;padding:0;margin:0 0 .75rem;font-size:.875rem}
.copy{font:inherit;font-size:.875rem;min-height:44px;padding:.5rem 1rem;border-radius:8px;border:1px solid var(--border-strong);background:var(--surface-default);color:var(--text-default);cursor:pointer}
.copy:hover{background:var(--surface-subtle)}
.bar-track{display:flex;height:48px;border-radius:8px;overflow:hidden;border:1px solid var(--border-subtle)}
.legend{list-style:none;padding:0;display:flex;flex-wrap:wrap;gap:.25rem 1.25rem}
.specimen-row{border-bottom:1px solid var(--border-subtle);padding:1rem 0}
.specimen-sample{margin:0;max-width:none;overflow-wrap:anywhere}
.specimen-meta{margin:.25rem 0 0;font-size:.875rem;color:var(--text-muted)}
.spacing{list-style:none;padding:0}
.spacing li{display:flex;align-items:center;gap:.75rem;margin:.25rem 0}
.space-bar{display:inline-block;height:16px;background:var(--surface-brand);border-radius:2px}
.focus-demo{display:flex;flex-wrap:wrap;gap:1rem;margin:1rem 0}
.focus-tile{padding:2rem;border-radius:8px;border:1px solid var(--border-subtle)}
.fake-btn{display:inline-block;padding:.75rem 1.25rem;border-radius:8px;background:%BRAND%;color:#fff;font-weight:600}
.fake-btn.on-brand{background:#fff;color:%BRAND%}
.callout{border-left:6px solid var(--border-strong);background:var(--surface-subtle);padding:.75rem 1rem;margin:1rem 0;border-radius:0 8px 8px 0}
.callout>:first-child{margin-top:0}.callout>:last-child{margin-bottom:0}
.callout-do{border-left-color:var(--success-border)}
.callout-dont{border-left-color:var(--error-border)}
.callout-a11y{border-left-color:var(--info-border)}
.callout-warn{border-left-color:var(--warning-border)}
blockquote{margin:1rem 0;padding-left:1rem;border-left:4px solid var(--border-strong)}
.site-footer{border-top:1px solid var(--border-subtle);padding:2rem 1rem;color:var(--text-muted);font-size:.875rem}
.site-footer .inner{max-width:1200px;margin:0 auto}
@media (prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important;animation:none!important}}
@media print{
@page{size:A4;margin:16mm 15mm 18mm;@bottom-right{content:counter(page) " / " counter(pages);font-size:9pt;color:#555}}
html,body{-webkit-print-color-adjust:exact;print-color-adjust:exact}
body{font-size:10.5pt;line-height:1.5}
.skip-link,.copy{display:none!important}
.site-header{min-height:240mm;display:flex;align-items:center;border:0;background:var(--surface-subtle);break-after:page}
.site-header img{max-height:120px;max-width:60%}
.site-header h1{font-size:34pt}
.layout{display:block;padding:0}
.toc{position:static;max-height:none;overflow:visible;break-after:page}
.toc h2{font-size:18pt;text-transform:none;letter-spacing:0;color:inherit;margin-bottom:6mm}
.toc ol{list-style:decimal;padding-left:8mm;columns:2;column-gap:10mm}
.toc a{padding:1mm 0;color:inherit}
main{max-width:none}
main section{break-before:page;border:0;margin:0;padding:0}
main h2{font-size:24pt}
h2,h3,h4{break-after:avoid}
figure,.fig,.bar,table,tr,.swatch,.callout,.specimen-row,.focus-demo,pre{break-inside:avoid}
.gallery{grid-template-columns:repeat(3,1fr)}
.gallery-sm{grid-template-columns:repeat(4,1fr)}
.swatches{grid-template-columns:repeat(3,1fr)}
.table-wrap{overflow:visible}
a{color:inherit}
main a[href^="http"]::after{content:" (" attr(href) ")";font-size:.8em}
.site-footer{display:none}
}
"""

PAGE_JS = """
// Only tables that actually scroll sideways become focusable regions (keyboard scrolling without extra tab stops).
function markScrollers(){
  document.querySelectorAll('.table-wrap').forEach(function(w){
    if (w.scrollWidth > w.clientWidth + 1) { w.setAttribute('tabindex','0'); w.setAttribute('role','region'); w.setAttribute('aria-label', w.getAttribute('data-label')); }
    else { w.removeAttribute('tabindex'); w.removeAttribute('role'); w.removeAttribute('aria-label'); }
  });
}
markScrollers(); window.addEventListener('resize', markScrollers);
document.querySelectorAll('button.copy').forEach(function(btn){
  btn.addEventListener('click', function(){
    var v = btn.getAttribute('data-copy'), live = document.getElementById('live');
    var done = function(){ live.textContent = 'Copied ' + v; };
    if (navigator.clipboard) { navigator.clipboard.writeText(v).then(done, function(){ live.textContent = 'Copy failed. The value is ' + v; }); }
    else { live.textContent = 'The value is ' + v; }
  });
});
"""


def header_logo(d: Data) -> str:
    """<picture> that swaps to the reversed logo in dark mode, so the header logo keeps its contrast."""
    paths = [f["path"] for f in d.manifest["files"]]

    def find(*suffixes):
        return next((p for s in suffixes for p in paths if p.endswith(s)), None)

    light_bg = d.sem["light"]["surface-subtle"]
    variant = next((t["recommendedVariant"] for t in d.manifest.get("backgroundTests", []) if t["background"] == "light-neutral"), None)
    if variant is None:  # No raster tests: use full colour only if every logo colour is >= 3:1 on the header.
        cols = d.brand.get("color", {}).get("brand", [])
        variant = "full-colour" if all(bl.contrast_ratio(c["hex"], light_bg) >= 3 for c in cols) else "mono-dark"
    solid = d.brand["logo"].get("monoStyle") == "solid"
    knock = () if solid or not variant.startswith("mono") else (f"primary-{variant}-knockout.png",)
    light = find(*knock, f"primary-{variant}.svg", f"primary-{variant}.png", "primary-full-colour.svg", "primary-full-colour.png") or d.brand["logo"]["master"]
    dark = find(*(() if solid else ("primary-mono-light-knockout.png",)), "primary-mono-light.svg", "primary-mono-light.png")
    alt = ""  # The h1 right beside it already names the organisation; repeating it adds noise.
    # Two images toggled by CSS (not <picture>): browsers pick <picture> sources once at load,
    # so a dark-mode viewer printing to PDF would otherwise get the reversed logo on paper.
    light_img = f'<img class="logo-light" src="{html.escape(light, quote=True)}" alt="{alt}">'
    dark_img = f'<img class="logo-dark" src="{html.escape(dark, quote=True)}" alt="{alt}">' if dark else ""
    return light_img + dark_img


def render(brand_path: Path, pdf: bool = False) -> dict:
    d = Data(brand_path)
    b = d.brand
    meta = b["meta"]
    content_dir = d.root / b.get("content", {}).get("dir", "content")
    chapter_files = sorted(content_dir.glob("*.md"), key=lambda p: (CHAPTER_STEMS.index(p.stem) if p.stem in CHAPTER_STEMS else 99, p.name))
    slug = Slugger()
    toc: list = []
    sections_html, sections_md = [], []
    unknown: list[str] = []

    for path in chapter_files:
        md = path.read_text(encoding="utf-8")

        def render_ph(name, level):
            fn = PLACEHOLDER_FUNCS.get(name)
            if not fn:
                unknown.append(f"{path.name}: {{{{{name}}}}}")
                return ""
            return blocks_html(fn(d), slug, level)

        body = md_to_html(md, slug, render_ph, shift=1, toc=toc)
        first = re.search(r'<h2 id="([^"]+)"', body)
        aria = f' aria-labelledby="{first.group(1)}"' if first else ""
        sections_html.append(f"<section{aria}>\n{body}\n</section>")

        def md_ph(m):
            fn = PLACEHOLDER_FUNCS.get(m.group(1))
            return blocks_md(fn(d)) if fn else m.group(0)

        md_clean = re.sub(r"<!--.*?-->\n?", "", md, flags=re.S)
        sections_md.append(re.sub(r"^#", "##", re.sub(r"^\{\{([\w.]+)\}\}\s*$", md_ph, md_clean, flags=re.M), flags=re.M))

    tokens_css = generate_tokens.css_file(generate_tokens.collect(b))
    css = PAGE_CSS.replace("%DARK%", d.sem["light"]["surface-inverse"]).replace("%BRAND%", d.sem["light"]["surface-brand"])
    # Print and PDF always use the light theme, whatever the viewer's colour scheme.
    css += "@media print{:root,:root:not([data-theme=\"light\"]),[data-theme=\"dark\"]{" + "".join(
        f"--{k}:{v}!important;" for k, v in d.sem["light"].items()) + "}}\n"
    nav = "".join(f'<li><a href="#{hid}">{html.escape(text)}</a></li>' for level, hid, text in toc if level == 2)
    title = f"{meta['name']} brand guidelines"
    page = f"""<!doctype html>
<html lang="{html.escape(meta.get('locale', 'en'))}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
<meta name="description" content="Brand identity, accessibility and social media guidelines for {html.escape(meta['name'])}.">
<meta name="color-scheme" content="light dark">
{google_fonts_link(b)}
<style>
{tokens_css}
{css}
</style>
</head>
<body>
<a class="skip-link" href="#main">Skip to main content</a>
<header class="site-header">
  <div class="inner">
    {header_logo(d)}
    <h1>{html.escape(title[0].upper() + title[1:])}</h1>
    <p>Version {html.escape(meta.get('version', ''))} · Updated {html.escape(meta.get('lastUpdated', ''))} · {html.escape(meta.get('accessibilityTarget', ''))}</p>
  </div>
</header>
<div class="layout">
  <nav class="toc" aria-label="Guide contents"><h2>Contents</h2><ol>{nav}</ol></nav>
  <main id="main" tabindex="-1">
{chr(10).join(sections_html)}
  </main>
</div>
<footer class="site-footer"><div class="inner">
  <p>{html.escape(meta['name'])} brand guidelines, version {html.escape(meta.get('version', ''))}. Questions: {inline(meta.get('contact', ''))}. Owner: {html.escape(meta.get('owner', ''))}.</p>
</div></footer>
<div id="live" class="visually-hidden" aria-live="polite"></div>
<script>{PAGE_JS}</script>
</body>
</html>
"""
    out_html = d.root / "style-guide.html"
    out_html.write_text(page, encoding="utf-8")
    md_doc = (f"# {title[0].upper() + title[1:]}\n\nVersion {meta.get('version', '')} · Updated {meta.get('lastUpdated', '')} · "
              f"{meta.get('accessibilityTarget', '')}\n\n## Contents\n\n" +
              "\n".join(f"{n}. [{t}](#{h})" for n, (lvl, h, t) in enumerate([x for x in toc if x[0] == 2], 1)) +
              "\n\n" + "\n\n".join(sections_md) + "\n")
    out_md = d.root / "style-guide.md"
    out_md.write_text(md_doc, encoding="utf-8")
    result = {"html": str(out_html), "markdown": str(out_md), "chapters": len(chapter_files), "unknownPlaceholders": unknown}
    if pdf:
        result["pdf"] = print_pdf(out_html)
    return result


def print_pdf(html_path: Path):
    candidates = ["google-chrome", "chromium", "chromium-browser", "microsoft-edge",
                  "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
                  "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
                  "/Applications/Chromium.app/Contents/MacOS/Chromium"]
    for c in candidates:
        exe = shutil.which(c) or (c if Path(c).exists() else None)
        if not exe:
            continue
        out = html_path.with_suffix(".pdf")
        try:
            subprocess.run([exe, "--headless=new", "--disable-gpu", "--no-pdf-header-footer", "--generate-pdf-document-outline", "--export-tagged-pdf",
                            f"--print-to-pdf={out}", html_path.resolve().as_uri()], check=True, capture_output=True, timeout=120)
            return str(out)
        except Exception as exc:  # pragma: no cover - environment dependent
            return f"PDF export failed: {exc}"
    return "No headless Chrome/Edge found; open style-guide.html and use Print > Save as PDF."


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("brand", type=Path)
    ap.add_argument("--pdf", action="store_true")
    args = ap.parse_args(argv)
    result = render(args.brand.resolve(), args.pdf)
    print(json.dumps(result, indent=2))
    return 1 if result["unknownPlaceholders"] else 0


if __name__ == "__main__":
    sys.exit(main())
